In [63]:
import numpy as np
import pandas as pd

df = pd.read_csv(r"C:\practice\Fraud_Detection_Analysis\experiments\Bank_Transaction_Fraud_Detection.csv")

df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Bank_Branch,Account_Type,Transaction_ID,Transaction_Date,...,Merchant_Category,Account_Balance,Transaction_Device,Transaction_Location,Device_Type,Is_Fraud,Transaction_Currency,Customer_Contact,Transaction_Description,Customer_Email
0,d5f6ec07-d69e-4f47-b9b4-7c58ff17c19e,Osha Tella,Male,60,Kerala,Thiruvananthapuram,Thiruvananthapuram Branch,Savings,4fa3208f-9e23-42dc-b330-844829d0c12c,23-01-2025,...,Restaurant,74557.27,Voice Assistant,"Thiruvananthapuram, Kerala",POS,0,INR,+9198579XXXXXX,Bitcoin transaction,oshaXXXXX@XXXXX.com
1,7c14ad51-781a-4db9-b7bd-67439c175262,Hredhaan Khosla,Female,51,Maharashtra,Nashik,Nashik Branch,Business,c9de0c06-2c4c-40a9-97ed-3c7b8f97c79c,11-01-2025,...,Restaurant,74622.66,POS Mobile Device,"Nashik, Maharashtra",Desktop,0,INR,+9191074XXXXXX,Grocery delivery,hredhaanXXXX@XXXXXX.com
2,3a73a0e5-d4da-45aa-85f3-528413900a35,Ekani Nazareth,Male,20,Bihar,Bhagalpur,Bhagalpur Branch,Savings,e41c55f9-c016-4ff3-872b-cae72467c75c,25-01-2025,...,Groceries,66817.99,ATM,"Bhagalpur, Bihar",Desktop,0,INR,+9197745XXXXXX,Mutual fund investment,ekaniXXX@XXXXXX.com
3,7902f4ef-9050-4a79-857d-9c2ea3181940,Yamini Ramachandran,Female,57,Tamil Nadu,Chennai,Chennai Branch,Business,7f7ee11b-ff2c-45a3-802a-49bc47c02ecb,19-01-2025,...,Entertainment,58177.08,POS Mobile App,"Chennai, Tamil Nadu",Mobile,0,INR,+9195889XXXXXX,Food delivery,yaminiXXXXX@XXXXXXX.com
4,3a4bba70-d9a9-4c5f-8b92-1735fd8c19e9,Kritika Rege,Female,43,Punjab,Amritsar,Amritsar Branch,Savings,f8e6ac6f-81a1-4985-bf12-f60967d852ef,30-01-2025,...,Entertainment,16108.56,Virtual Card,"Amritsar, Punjab",Mobile,0,INR,+9195316XXXXXX,Debt repayment,kritikaXXXX@XXXXXX.com

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 24 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Customer_ID              200000 non-null  object
 1   Customer_Name            200000 non-null  object
 2   Gender                   200000 non-null  object
 3   Age                      200000 non-null  int64
 4   State                    200000 non-null  object
 5   City                     200000 non-null  object
 6   Bank_Branch              200000 non-null  object
 7   Account_Type             200000 non-null  object
 8   Transaction_ID           200000 non-null  object
 9   Transaction_Date         200000 non-null  object
 10  Transaction_Time         200000 non-null  object
 11  Transaction_Amount       200000 non-null  float64
 12  Merchant_ID              200000 non-null  object
 13  Transaction_Type         200000 non-null  object
 14  Merchant_Category        200000 non-null  object
 15  Account_Balance          200000 non-null  float64
 16  Transaction_Device       200000 non-null  object
 17  Transaction_Location     200000 non-null  object
 18  Device_Type              200000 non-null  object
 19  Is_Fraud                 200000 non-null  int64
 20  Transaction_Currency     200000 non-null  object
 21  Customer_Contact         200000 non-null  object
 22  Transaction_Description  200000 non-null  object
 23  Customer_Email           200000 non-null  object
dtypes: float64(2), int64(2), object(20)
memory usage: 36.6+ MB

In [65]:
df.shape

(200000, 24)

In [66]:
df['Transaction_Description'].nunique()

172

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 24 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Customer_ID              200000 non-null  object
 1   Customer_Name            200000 non-null  object
 2   Gender                   200000 non-null  object
 3   Age                      200000 non-null  int64
 4   State                    200000 non-null  object
 5   City                     200000 non-null  object
 6   Bank_Branch              200000 non-null  object
 7   Account_Type             200000 non-null  object
 8   Transaction_ID           200000 non-null  object
 9   Transaction_Date         200000 non-null  object
 10  Transaction_Time         200000 non-null  object
 11  Transaction_Amount       200000 non-null  float64
 12  Merchant_ID              200000 non-null  object
 13  Transaction_Type         200000 non-null  object
 14  Merchant_Category        200000 non-null  object
 15  Account_Balance          200000 non-null  float64
 16  Transaction_Device       200000 non-null  object
 17  Transaction_Location     200000 non-null  object
 18  Device_Type              200000 non-null  object
 19  Is_Fraud                 200000 non-null  int64
 20  Transaction_Currency     200000 non-null  object
 21  Customer_Contact         200000 non-null  object
 22  Transaction_Description  200000 non-null  object
 23  Customer_Email           200000 non-null  object
dtypes: float64(2), int64(2), object(20)
memory usage: 36.6+ MB

In [68]:
df.isnull().sum()

Customer_ID                0
Customer_Name              0
Gender                     0
Age                        0
State                      0
City                       0
Bank_Branch                0
Account_Type               0
Transaction_ID             0
Transaction_Date           0
Transaction_Time           0
Transaction_Amount         0
Merchant_ID                0
Transaction_Type           0
Merchant_Category          0
Account_Balance            0
Transaction_Device         0
Transaction_Location       0
Device_Type                0
Is_Fraud                   0
Transaction_Currency       0
Customer_Contact           0
Transaction_Description    0
Customer_Email             0
dtype: int64

In [ ]:
drop_cols = [
    "Customer_ID",
    "Customer_Name",
    "Transaction_ID",
    "Customer_Contact",
    "Customer_Email",
    "Merchant_ID",
    "Transaction_Description",
    "Transaction_Currency"
]

df = df.drop(columns=drop_cols)

In [70]:
df["Is_Fraud"].value_counts()

Is_Fraud
0    189912
1     10088
Name: count, dtype: int64

In [71]:
df["Is_Fraud"].value_counts(normalize=True)

Is_Fraud
0    0.94956
1    0.05044
Name: proportion, dtype: float64

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 17 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Gender                200000 non-null  object
 1   Age                   200000 non-null  int64
 2   State                 200000 non-null  object
 3   City                  200000 non-null  object
 4   Bank_Branch           200000 non-null  object
 5   Account_Type          200000 non-null  object
 6   Transaction_Date      200000 non-null  object
 7   Transaction_Time      200000 non-null  object
 8   Transaction_Amount    200000 non-null  float64
 9   Transaction_Type      200000 non-null  object
 10  Merchant_Category     200000 non-null  object
 11  Account_Balance       200000 non-null  float64
 12  Transaction_Device    200000 non-null  object
 13  Transaction_Location  200000 non-null  object
 14  Device_Type           200000 non-null  object
 15  Is_Fraud              200000 non-null  int64
 16  Transaction_Currency  200000 non-null  object
dtypes: float64(2), int64(2), object(13)
memory usage: 25.9+ MB

In [ ]:
nominal_cols = [
    'Gender',
    'State',
    'Account_Type',
    'Transaction_Type',
    'Merchant_Category',
    'Transaction_Device',
    'Device_Type',

]

df = pd.get_dummies(df, columns=nominal_cols, drop_first=True)

In [75]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

categorical_cols = [
    'City',
    'Bank_Branch',
    'Transaction_Location'
]

for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

In [76]:
df

,Age,City,Bank_Branch,Transaction_Date,Transaction_Time,Transaction_Amount,Account_Balance,Transaction_Location,Is_Fraud,Transaction_Currency,...,Transaction_Device_Self-service Banking Machine,Transaction_Device_Smart Card,Transaction_Device_Tablet,Transaction_Device_Virtual Card,Transaction_Device_Voice Assistant,Transaction_Device_Wearable Device,Transaction_Device_Web Browser,Device_Type_Desktop,Device_Type_Mobile,Device_Type_POS
0,60,127,127,23-01-2025,16:04:07,32415.45,74557.27,129,0,INR,...,False,False,False,False,True,False,False,False,False,True
1,51,100,100,11-01-2025,17:14:53,43622.60,74622.66,102,0,INR,...,False,False,False,False,False,False,False,True,False,False
2,20,13,13,25-01-2025,03:09:52,63062.56,66817.99,13,0,INR,...,False,False,False,False,False,False,False,True,False,False
3,57,22,22,19-01-2025,12:27:02,14000.72,58177.08,24,0,INR,...,False,False,False,False,False,False,False,False,True,False
4,43,7,7,30-01-2025,18:30:46,18335.16,16108.56,7,0,INR,...,False,False,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,55,33,33,08-01-2025,18:42:09,98513.74,37475.11,35,0,INR,...,False,False,False,False,False,False,False,False,False,False
199996,51,63,63,01-01-2025,20:51:21,40593.55,53037.20,65,0,INR,...,False,False,False,False,False,False,False,False,False,False
199997,41,21,21,28-01-2025,10:47:40,61579.70,96225.36,21,0,INR,...,False,False,False,False,False,False,False,True,False,False
199998,28,103,103,08-01-2025,06:26:41,39488.22,89599.90,105,0,INR,...,False,False,False,False,True,False,False,True,False,False
199999,34,71,71,08-01-2025,15:26:19,58622.49,15066.24,73,0,INR,...,False,False,False,True,False,False,False,False,True,False

In [74]:
legit = df[df.Is_Fraud==0]
fraud = df[df.Is_Fraud==1]

In [21]:
print(legit.shape)
print(fraud.shape)

(189912, 19)
(10088, 19)

In [23]:
legit.Transaction_Amount.describe()

count    189912.000000
mean      49551.831380
std       28541.881772
min          10.290000
25%       24877.685000
50%       49517.420000
75%       74326.872500
max       98999.980000
Name: Transaction_Amount, dtype: float64

In [24]:
fraud.Transaction_Amount.describe()

count    10088.000000
mean     49277.925242
std      28739.518843
min         10.410000
25%      24420.042500
50%      49162.945000
75%      74068.717500
max      98999.020000
Name: Transaction_Amount, dtype: float64

In [11]:
df['Amount_Balance_Ratio'] = (
    df['Transaction_Amount'] /
    (df['Account_Balance'] + 1)
)

In [12]:
df['Remaining_Balance'] = (
    df['Account_Balance'] -
    df['Transaction_Amount']
)

In [13]:
import numpy as np

df['Log_Transaction_Amount'] = np.log1p(
    df['Transaction_Amount']
)

In [14]:
merchant_risk = df.groupby('Merchant_Category')['Is_Fraud'].mean()

df['Merchant_Fraud_Rate'] = (
    df['Merchant_Category']
    .map(merchant_risk)
)

In [15]:
city_risk = df.groupby('City')['Is_Fraud'].mean()

df['City_Fraud_Rate'] = (
    df['City']
    .map(city_risk)
)

In [16]:
state_risk = df.groupby('State')['Is_Fraud'].mean()

df['State_Fraud_Rate'] = (
    df['State']
    .map(state_risk)
)

In [17]:
device_risk = (
    df.groupby('Transaction_Device')['Is_Fraud']
    .mean()
)

df['Device_Fraud_Rate'] = (
    df['Transaction_Device']
    .map(device_risk)
)

In [20]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

categorical_cols = [
    'Gender',
    'State',
    'City',
    'Bank_Branch',
    'Account_Type',
    'Merchant_ID',
    'Transaction_Type',
    'Merchant_Category',
    'Transaction_Device',
    'Transaction_Location',
    'Device_Type',
    'Transaction_Currency',
    'Transaction_Period'
]

for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

In [33]:
from sklearn.ensemble import RandomForestClassifier
X = df.drop(
    columns=[
        'Is_Fraud',
        'Transaction_Date',
        'Transaction_Time',
        'Transaction_Description'
    ],
    errors='ignore'
)

y = df['Is_Fraud']

rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

rf.fit(X, y)

importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': rf.feature_importances_
})

importance = importance.sort_values(
    'Importance',
    ascending=False
)

print(importance.head(20))

                   Feature  Importance
7              Merchant_ID    0.077680
10         Account_Balance    0.072759
6       Transaction_Amount    0.071230
22  Log_Transaction_Amount    0.070930
21       Remaining_Balance    0.070507
20    Amount_Balance_Ratio    0.069731
1                      Age    0.057609
16         Transaction_Day    0.046308
15        Transaction_Hour    0.046003
26       Device_Fraud_Rate    0.036089
11      Transaction_Device    0.034478
24         City_Fraud_Rate    0.034237
12    Transaction_Location    0.028421
3                     City    0.028221
25        State_Fraud_Rate    0.028084
4              Bank_Branch    0.027990
2                    State    0.027684
18     Transaction_Weekday    0.027593
8         Transaction_Type    0.024371
9        Merchant_Category    0.022994

In [34]:
top_features = [
    'Merchant_ID',
    'Account_Balance',
    'Transaction_Amount',
    'Log_Transaction_Amount',
    'Remaining_Balance',
    'Amount_Balance_Ratio',
    'Age',
    'Transaction_Day',
    'Transaction_Hour',
    'Device_Fraud_Rate',
    'Transaction_Device',
    'City_Fraud_Rate',
    'Transaction_Location',
    'City',
    'State_Fraud_Rate',
    'Bank_Branch',
    'State',
    'Transaction_Weekday',
    'Transaction_Type',
    'Merchant_Category'
]

X = df[top_features]
y = df['Is_Fraud']

In [35]:
print("\nMissing Values:")
print(df.isnull().sum())

Missing Values:
Gender                     0
Age                        0
State                      0
City                       0
Bank_Branch                0
Account_Type               0
Transaction_Date           0
Transaction_Time           0
Transaction_Amount         0
Merchant_ID                0
Transaction_Type           0
Merchant_Category          0
Account_Balance            0
Transaction_Device         0
Transaction_Location       0
Device_Type                0
Is_Fraud                   0
Transaction_Currency       0
Transaction_Description    0
Transaction_Hour           0
Transaction_Day            0
Transaction_Month          0
Transaction_Weekday        0
Is_Weekend                 0
Amount_Balance_Ratio       0
Remaining_Balance          0
Log_Transaction_Amount     0
Merchant_Fraud_Rate        0
City_Fraud_Rate            0
State_Fraud_Rate           0
Device_Fraud_Rate          0
High_Amount_Flag           0
Transaction_Period         0
dtype: int64

In [36]:
df

,Gender,Age,State,City,Bank_Branch,Account_Type,Transaction_Date,Transaction_Time,Transaction_Amount,Merchant_ID,...,Is_Weekend,Amount_Balance_Ratio,Remaining_Balance,Log_Transaction_Amount,Merchant_Fraud_Rate,City_Fraud_Rate,State_Fraud_Rate,Device_Fraud_Rate,High_Amount_Flag,Transaction_Period
0,1,60,15,127,127,2,2025-01-23,1900-01-01 16:04:07,32415.45,25908,...,0,0.434767,42141.82,10.386421,0.050350,0.048246,0.045340,0.051250,0,0
1,0,51,18,100,100,0,2025-01-11,1900-01-01 17:14:53,43622.60,195310,...,1,0.584568,31000.06,10.683354,0.050350,0.048000,0.050830,0.050712,0,0
2,1,20,4,13,13,2,2025-01-25,1900-01-01 03:09:52,63062.56,118512,...,1,0.943782,3755.43,11.051898,0.051888,0.042142,0.046611,0.048726,0,3
3,0,57,28,22,22,0,2025-01-19,1900-01-01 12:27:02,14000.72,191023,...,1,0.240653,44176.36,9.546935,0.048233,0.050818,0.056155,0.049695,0,0
4,0,43,25,7,7,2,2025-01-30,1900-01-01 18:30:46,18335.16,88278,...,0,1.138154,-2226.60,9.816630,0.048233,0.043515,0.047192,0.054473,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,0,55,7,33,33,0,2025-01-08,1900-01-01 18:42:09,98513.74,89534,...,0,2.628708,-61038.63,11.497961,0.050350,0.050026,0.052074,0.051012,1,1
199996,1,51,19,63,63,0,2025-01-01,1900-01-01 20:51:21,40593.55,6533,...,0,0.765364,12443.65,10.611389,0.051888,0.047883,0.050605,0.048726,0,1
199997,0,41,5,21,21,2,2025-01-28,1900-01-01 10:47:40,61579.70,127455,...,0,0.639946,34645.66,11.028104,0.049852,0.047941,0.049681,0.048726,0,2
199998,0,28,29,103,103,1,2025-01-08,1900-01-01 06:26:41,39488.22,6880,...,0,0.440712,50111.68,10.583783,0.050316,0.055461,0.052923,0.051250,0,2
199999,1,34,22,71,71,0,2025-01-08,1900-01-01 15:26:19,58622.49,175704,...,0,3.890725,-43556.25,10.978891,0.050316,0.039843,0.051733,0.054473,0,0

In [26]:
print("\nFraud Distribution:")
print(y.value_counts())

print("\nFinal Dataset Shape:", df.shape)

Fraud Distribution:
Is_Fraud
0    189912
1     10088
Name: count, dtype: int64

Final Dataset Shape: (200000, 33)

In [47]:
print(df['Is_Fraud'].value_counts())

Is_Fraud
0    189912
1     10088
Name: count, dtype: int64

In [37]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify = y
)

In [38]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)

X_resampled, y_resampled = smote.fit_resample(X_train, y_train)

In [39]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_resampled)
X_test = scaler.transform(X_test)

In [40]:
print(y_resampled.value_counts())
print(y_test.value_counts())

Is_Fraud
0    151930
1    151930
Name: count, dtype: int64
Is_Fraud
0    37982
1     2018
Name: count, dtype: int64

In [44]:
X_train.shape

(303860, 20)

In [45]:
y_resampled.shape

(303860,)

In [31]:
import dagshub
import mlflow

dagshub.init(
    repo_owner="Shrutichauha7",
    repo_name="Fraud_Detection_Analysis",
    mlflow=True
)

mlflow.set_experiment("LogisticRegression Baseline")

with mlflow.start_run():
    mlflow.log_param("parameter name", "value")
    mlflow.log_metric("metric name", 1)

print("Run logged successfully")

RemoteProtocolError: Server disconnected without sending a response.

In [46]:
import mlflow
import logging
import os
import time

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)

logging.info("Starting MLflow run...")

with mlflow.start_run():

    start_time = time.time()

    try:
        
        logging.info("Logging Preprocessing Parameters")

        mlflow.log_param("model", "LogisticRegression")
        mlflow.log_param("test_size", 0.2)
        

        logging.info("Training model...")
        model = LogisticRegression(max_iter=1000)
        model.fit(X_train, y_resampled)


        logging.info("Making predictions...")
        y_pred = model.predict(X_test)

       
        accuracy = accuracy_score(y_test, y_pred)
        precision = precision_score(y_test, y_pred)
        recall = recall_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred)
        auc = roc_auc_score(y_test, y_pred)

       
        logging.info("Logging metrics...")

        mlflow.log_metric("accuracy", accuracy)
        mlflow.log_metric("precision", precision)
        mlflow.log_metric("recall", recall)
        mlflow.log_metric("f1_score", f1)

        logging.info("Saving model...")

        mlflow.sklearn.log_model(
            model,"model"
        )


        execution_time = time.time() - start_time

        mlflow.log_metric(
            "execution_time_seconds",
            execution_time
        )

        logging.info(f"Accuracy: {accuracy}")
        logging.info(f"Precision: {precision}")
        logging.info(f"Recall: {recall}")
        logging.info(f"F1 Score: {f1}")
        logging.info(f"ROC-AUC: {auc}")

        print("MLflow Run Completed Successfully!")

    except Exception as e:

        logging.error(f"Error occurred: {e}")

        mlflow.log_param("error", str(e))

        raise

2026-06-08 17:43:12,917 - INFO - Starting MLflow run...
2026-06-08 17:43:13,129 - INFO - Logging Preprocessing Parameters
2026-06-08 17:43:13,173 - INFO - Training model...
2026-06-08 17:43:13,502 - INFO - Making predictions...
2026-06-08 17:43:13,547 - INFO - Logging metrics...
2026-06-08 17:43:13,607 - INFO - Saving model...
2026/06/08 17:43:13 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/06/08 17:43:13 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026-06-08 17:43:20,810 - INFO - Accuracy: 0.582825
2026-06-08 17:43:20,818 - INFO - Precision: 0.05340071850453632
2026-06-08 17:43:20,818 - INFO - Recall: 0.4345887016848365
2026-06-08 17:43:20,818 - INFO - F1 Score: 0.09511414782278618
2026-06-08 17:43:20,818 - INFO - ROC-AUC: 0.5126447799930685

MLflow Run Completed Successfully!